checks:
    javascript:
        code-style: true
        complexity: true
        duplicate-code: true

build:
    nodes:
        analysis:
            environment:
                node: 16 # Specify the Node.js version
            project_setup:
                override: false # Use default setup to fetch and install dependencies
            tests:
                override: true
                commands:
                    - npm install
                    - npm run lint
                    - npm test

filter:
    paths:
        - "src/" # Ensure it matches the actual location of your source code
        - "tests/" # Include tests if you want them analyzed

tools:
    eslint: true
    node-security: true

notifications:
    email:
        on_success: never
        on_failure: always