checks:
    javascript: true

build:
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
filter:
    paths:
        - "src/" # Include the directory containing your source code
        - "tests/" # Optionally include tests if you want them analyzed