checks:
    javascript: true

build:
    nodes:
        my-tests:
            environment:
                node:
                    version: 16 # Specify the Node.js version you are using
        analysis:
            tests:
                override:
                    - js-scrutinizer-run # Run the Scrutinizer analysis
filter:
    paths:
        - "src/" # Include the directory containing your source code
        - "**/*.jsx" # Include JSX files

 checks:
    javascript: true

build:
    nodes:
        my-tests:
            environment:
                node:
                    version: 16
        analysis:
            project_setup:
                override:
                    - npm install
            tests:
                override:
                    - npm run lint # Ensure lint script targets JSX
                    - npm run test # If applicable
                    - js-scrutinizer-run # Analyze with Scrutinizer

filter:
    paths:
        - "src/"
        - "**/*.jsx"

notifications:
    email:
        on_success: never
        on_failure: always