checks:
    javascript:
        code-style: true
        complexity: true
        duplicate-code: true

build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [js-scrutinizer-run]