tools:
  eslint:
    config: eslint.config.js
  node-security:
    enabled: true

build:
  nodes:
    runtime: "nodejs:16" # Specify the Node.js runtime directly
  commands:
    - npm install 
    - npm run lint

checks:
  javascript:
    code-style:
      enabled: true
      config: eslint
    complexity:
      enabled: true
      max-complexity: 10
  node:
    dependencies:
      enabled: true
    duplicate-packages:
      enabled: true
  react:
    best-practices:
      enabled: true

filter:
  paths:
    - "src/"

notifications:
  email:
    on_success: never 
    on_failure: always